name: contacts_fetch
description: "A Flutter project for fetching and managing contacts."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  # Networking and API
  http: ^1.3.0
  # Location and Geocoding
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  # Animation and UI Effects
  lottie: ^3.3.1
  # State Management
  provider: ^6.1.4
  # Internationalization
  intl: ^0.20.2
  # Environment Variables
  flutter_dotenv: ^5.2.1
  # Contacts fetching and management
  flutter_screenutil:
  permission_handler: ^11.4.0
  flutter_contacts:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section (uncomment and add if needed)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Fonts section (uncomment and add if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italicx